TICKER_METADATA = {
    "AAPL": {"company_name": "Apple", "sector": "Technology"},
    "MSFT": {"company_name": "Microsoft", "sector": "Technology"},
    "NVDA": {"company_name": "NVIDIA", "sector": "Technology"},
    "AMZN": {"company_name": "Amazon", "sector": "Consumer Discretionary"},
    "META": {"company_name": "Meta Platforms", "sector": "Technology"},
    "GOOGL": {"company_name": "Alphabet Class A", "sector": "Communication Services"},
    "GOOG": {"company_name": "Alphabet Class C", "sector": "Communication Services"},
    "TSLA": {"company_name": "Tesla", "sector": "Consumer Discretionary"},
    "BRK-B": {"company_name": "Berkshire Hathaway", "sector": "Financials"},
    "JPM": {"company_name": "JPMorgan Chase", "sector": "Financials"},
    "V": {"company_name": "Visa", "sector": "Financials"},
    "MA": {"company_name": "Mastercard", "sector": "Financials"},
    "XOM": {"company_name": "Exxon Mobil", "sector": "Energy"},
    "LLY": {"company_name": "Eli Lilly", "sector": "Health Care"},
    "AVGO": {"company_name": "Broadcom", "sector": "Technology"},
    "COST": {"company_name": "Costco", "sector": "Consumer Staples"},
    "WMT": {"company_name": "Walmart", "sector": "Consumer Staples"},
    "UNH": {"company_name": "UnitedHealth", "sector": "Health Care"},
    "HD": {"company_name": "Home Depot", "sector": "Consumer Discretionary"},
    "PG": {"company_name": "Procter & Gamble", "sector": "Consumer Staples"},
    "JNJ": {"company_name": "Johnson & Johnson", "sector": "Health Care"},
    "BAC": {"company_name": "Bank of America", "sector": "Financials"},
    "ABBV": {"company_name": "AbbVie", "sector": "Health Care"},
    "KO": {"company_name": "Coca-Cola", "sector": "Consumer Staples"},
    "PEP": {"company_name": "PepsiCo", "sector": "Consumer Staples"},
    "MRK": {"company_name": "Merck", "sector": "Health Care"},
    "CVX": {"company_name": "Chevron", "sector": "Energy"},
    "ADBE": {"company_name": "Adobe", "sector": "Technology"},
    "CRM": {"company_name": "Salesforce", "sector": "Technology"},
    "NFLX": {"company_name": "Netflix", "sector": "Communication Services"},
    "AMD": {"company_name": "AMD", "sector": "Technology"},
    "LIN": {"company_name": "Linde", "sector": "Materials"},
    "MCD": {"company_name": "McDonald's", "sector": "Consumer Discretionary"},
    "ORCL": {"company_name": "Oracle", "sector": "Technology"},
    "ACN": {"company_name": "Accenture", "sector": "Technology"},
    "TMO": {"company_name": "Thermo Fisher", "sector": "Health Care"},
    "CSCO": {"company_name": "Cisco", "sector": "Technology"},
    "ABT": {"company_name": "Abbott", "sector": "Health Care"},
    "WFC": {"company_name": "Wells Fargo", "sector": "Financials"},
    "IBM": {"company_name": "IBM", "sector": "Technology"},
    "GE": {"company_name": "GE Aerospace", "sector": "Industrials"},
    "INTU": {"company_name": "Intuit", "sector": "Technology"},
    "QCOM": {"company_name": "Qualcomm", "sector": "Technology"},
    "NOW": {"company_name": "ServiceNow", "sector": "Technology"},
    "DIS": {"company_name": "Disney", "sector": "Communication Services"},
    "CAT": {"company_name": "Caterpillar", "sector": "Industrials"},
    "DHR": {"company_name": "Danaher", "sector": "Health Care"},
    "AMGN": {"company_name": "Amgen", "sector": "Health Care"},
    "TXN": {"company_name": "Texas Instruments", "sector": "Technology"},
    "PM": {"company_name": "Philip Morris", "sector": "Consumer Staples"},
    "SPGI": {"company_name": "S&P Global", "sector": "Financials"},
    "RTX": {"company_name": "RTX", "sector": "Industrials"},
    "UBER": {"company_name": "Uber", "sector": "Industrials"},
    "GS": {"company_name": "Goldman Sachs", "sector": "Financials"},
    "ISRG": {"company_name": "Intuitive Surgical", "sector": "Health Care"},
    "BLK": {"company_name": "BlackRock", "sector": "Financials"},
    "PGR": {"company_name": "Progressive", "sector": "Financials"},
    "HON": {"company_name": "Honeywell", "sector": "Industrials"},
    "BKNG": {"company_name": "Booking", "sector": "Consumer Discretionary"},
    "AMAT": {"company_name": "Applied Materials", "sector": "Technology"},
    "SYK": {"company_name": "Stryker", "sector": "Health Care"},
    "LOW": {"company_name": "Lowe's", "sector": "Consumer Discretionary"},
    "AXP": {"company_name": "American Express", "sector": "Financials"},
    "TJX": {"company_name": "TJX", "sector": "Consumer Discretionary"},
    "MDT": {"company_name": "Medtronic", "sector": "Health Care"},
    "VRTX": {"company_name": "Vertex", "sector": "Health Care"},
    "ADP": {"company_name": "ADP", "sector": "Industrials"},
    "PLD": {"company_name": "Prologis", "sector": "Real Estate"},
    "LRCX": {"company_name": "Lam Research", "sector": "Technology"},
    "C": {"company_name": "Citigroup", "sector": "Financials"},
    "DE": {"company_name": "Deere", "sector": "Industrials"},
    "GILD": {"company_name": "Gilead", "sector": "Health Care"},
    "MMC": {"company_name": "Marsh McLennan", "sector": "Financials"},
    "ETN": {"company_name": "Eaton", "sector": "Industrials"},
    "NEE": {"company_name": "NextEra Energy", "sector": "Utilities"},
    "ADI": {"company_name": "Analog Devices", "sector": "Technology"},
    "MU": {"company_name": "Micron", "sector": "Technology"},
    "ANET": {"company_name": "Arista Networks", "sector": "Technology"},
    "CB": {"company_name": "Chubb", "sector": "Financials"},
    "TMUS": {"company_name": "T-Mobile", "sector": "Communication Services"},
    "SO": {"company_name": "Southern Co.", "sector": "Utilities"},
    "SCHW": {"company_name": "Charles Schwab", "sector": "Financials"},
    "CI": {"company_name": "Cigna", "sector": "Health Care"},
    "PANW": {"company_name": "Palo Alto Networks", "sector": "Technology"},
    "MO": {"company_name": "Altria", "sector": "Consumer Staples"},
    "BMY": {"company_name": "Bristol Myers Squibb", "sector": "Health Care"},
    "ZTS": {"company_name": "Zoetis", "sector": "Health Care"},
    "INTC": {"company_name": "Intel", "sector": "Technology"},
    "ELV": {"company_name": "Elevance Health", "sector": "Health Care"},
    "DUK": {"company_name": "Duke Energy", "sector": "Utilities"},
    "CMCSA": {"company_name": "Comcast", "sector": "Communication Services"},
    "T": {"company_name": "AT&T", "sector": "Communication Services"},
    "COP": {"company_name": "ConocoPhillips", "sector": "Energy"},
    "CL": {"company_name": "Colgate-Palmolive", "sector": "Consumer Staples"},
    "NKE": {"company_name": "Nike", "sector": "Consumer Discretionary"},
    "MMM": {"company_name": "3M", "sector": "Industrials"},
    "SHW": {"company_name": "Sherwin-Williams", "sector": "Materials"},
    "MDLZ": {"company_name": "Mondelez", "sector": "Consumer Staples"},
    "APD": {"company_name": "Air Products", "sector": "Materials"},
    "REGN": {"company_name": "Regeneron", "sector": "Health Care"},
    "UPS": {"company_name": "UPS", "sector": "Industrials"},
    "FI": {"company_name": "Fiserv", "sector": "Financials"},
    "PYPL": {"company_name": "PayPal", "sector": "Financials"},
    "AON": {"company_name": "Aon", "sector": "Financials"},
    "WM": {"company_name": "Waste Management", "sector": "Industrials"},
    "ICE": {"company_name": "Intercontinental Exchange", "sector": "Financials"},
}

TICKERS = list(TICKER_METADATA.keys())
